### ISSUE TITLE
 I try to run your example codes,but get an error.

### ISSUE THREAD

**Issue by zdlspace0528** [WWakker/xlincom#4]
I try to run your example codes,but get an error.My Stata version is 17.0 SE.Can you help to solve this problem?
Code:
       webuse gxmpl1
         reg gnp L(0/2).cpi
         xlincom (t = cpi) (t1 = cpi + l1.cpi) (t2 = cpi + l1.cpi + l2.cpi),repost
        r(9999);
        end of do-file
        r(9999);
Best regards.

Raymond Zhang
Stata 17.0,SE

**Comment by WWakker** [comment]
This was caused by a bug in Stata itself, introduced in Stata 16.

https://www.statalist.org/forums/forum/general-stata-discussion/general/1551533-new-on-ssc-mlincom-multiple-linear-combinations-of-parameters?p=1617860#post1617860
